# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=16)),
                ('theme', models.CharField(max_length=32)),
                ('formula', models.TextField()),
                ('comment', models.TextField()),
                ('order', models.FloatField()),
            ],
        ),
    ]
